name: to_do_list_2024_winter
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.2
  geocoding: ^2.1.1
  http: ^1.2.2


  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  firebase_storage: ^13.0.4
  cloud_firestore: ^6.1.0
  firebase_performance: ^0.11.1+2

  auto_size_text: 3.0.0
  cached_network_image: 3.3.1
  collection: ^1.19.1
  flutter_animate: 4.1.1+1
  flutter_cache_manager: 3.3.1
  flutter_plugin_android_lifecycle: 2.0.17
  font_awesome_flutter: 10.6.0
  from_css_color: 2.0.0
  go_router: 12.1.3
  google_fonts: ^6.2.1
  google_sign_in: 6.1.5
  image_picker: 1.0.4
  infinite_scroll_pagination: 4.0.0
  intl: ^0.20.2
  json_path: 0.6.2
  mime_type: 1.0.0
  page_transition: 2.1.0
  path_provider: 2.0.14
  plugin_platform_interface: 2.1.8
  provider: 6.0.5
  rxdart: 0.27.7
  shared_preferences: 2.2.2
  sign_in_with_apple: ^6.1.1
  sqflite: ^2.3.3+1
  stream_transform: 2.1.0
  timeago: 3.2.2
  url_launcher: 6.2.5
  video_player: 2.8.1

  cupertino_icons: ^1.0.0
  file_picker: ^8.3.2

dev_dependencies:
  flutter_lints: 3.0.0
  lints: 3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/

dependency_overrides:
  flutter_plugin_android_lifecycle: ^2.0.20
